version: '3.7'

networks:
  airflow-pyspark:
    driver: bridge
    name: airflow-pyspark
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1

services:

  fetch-data-nasa:
    build:
      context: services/fetch-data
      dockerfile: Dockerfile.nasadata
      args:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: fetch-data-nasa
    container_name: fetchdatanasa
    restart: "no"
    networks:
      airflow-pyspark:
        ipv4_address: 172.28.0.3
    volumes:
      - /tmp/dockerdata/:/tmp/
  
  spark-master:
    build:
      context: services/pyspark
      dockerfile: Dockerfile.pyspark
      args:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no 
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      airflow-pyspark:
        ipv4_address: 172.28.0.4
    volumes:
      - ./src/:/opt/bitnami/spark/src/
      - ./tests/:/opt/bitnami/spark/tests/
  
  spark-worker:
    build:
      context: services/pyspark
      dockerfile: Dockerfile.pyspark
      args:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker 
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no 
      - SPARK_RPC_ENCRYPTION_ENABLED=no 
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    networks:
      airflow-pyspark:
        ipv4_address: 172.28.0.5
    volumes:
      - ./src/:/opt/bitnami/spark/src/
      - ./tests/:/opt/bitnami/spark/tests/
    depends_on:
      - spark-master